name: E2E Tests
on:
    push:
        branches: [main]
    pull_request:

jobs:
    test:
        name: E2E Tests
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - name: Install dependencies
              run: bun install
            - name: Install Playwright browsers
              run: bun run test:install
            - name: Run Playwright tests
              run: bun run test
              env:
                  NODE_ENV: test
                  NEXT_PUBLIC_URL: http://localhost:3000
                  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
                  CONTENTFUL_ENVIRONMENT_ID: ${{ secrets.CONTENTFUL_ENVIRONMENT_ID }}
                  CONTENTFUL_DELIVERY_API_KEY: ${{ secrets.CONTENTFUL_DELIVERY_API_KEY }}
                  CONTENTFUL_PREVIEW_API_KEY: ${{ secrets.CONTENTFUL_PREVIEW_API_KEY }}
