name: E2E Tests
on:
    push:
        branches: [main]
    pull_request:
jobs:
    test:
        name: E2E Tests
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - name: Install dependencies
              run: bun install
            - name: Install Playwright browsers
              run: bun run test:install
            - name: Run Playwright tests
              run: bun run test
              env:
                  NODE_ENV: test
                  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
                  CONTENTFUL_DELIVERY_API_KEY: ${{ secrets.CONTENTFUL_DELIVERY_API_KEY }}
                  CONTENTFUL_PREVIEW_API_KEY: ${{ secrets.CONTENTFUL_PREVIEW_API_KEY }}
            - name: Upload test results
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: playwright-report
                  path: |
                      playwright-report/
                      test-results/
                  retention-days: 30
    test-mobile:
        name: Mobile E2E Tests
        runs-on: ubuntu-latest
        timeout-minutes: 20
        needs: test
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - name: Install dependencies
              run: bun install
            - name: Install Playwright browsers
              run: bun run test:install
            - name: Run mobile tests
              run: bunx playwright test --project="Mobile Chrome" --project="Mobile Safari"
              env:
                  NODE_ENV: test
                  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
                  CONTENTFUL_DELIVERY_API_KEY: ${{ secrets.CONTENTFUL_DELIVERY_API_KEY }}
                  CONTENTFUL_PREVIEW_API_KEY: ${{ secrets.CONTENTFUL_PREVIEW_API_KEY }}
            - name: Upload mobile test results
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: mobile-playwright-report
                  path: |
                      playwright-report/
                      test-results/
                  retention-days: 30
